### ISSUE TITLE
State not changed when a Entry method is call?

### ISSUE THREAD

**Issue by EasonPai** [hekailiang/squirrel#50]
Hi Henry~ 

I am confused why is State not changed when an Entry method is called?
or this is an issue? 

Take this test for example
https://github.com/hekailiang/squirrel/blob/master/squirrel-foundation/src/test/java/org/squirrelframework/foundation/fsm/samples/QuickStartSample.java

if I add a new line into function "ontoB" 
```java
protected void ontoB(String from, String to, FSMEvent event, Integer context) {
            System.out.println("Entry State \'"+to+"\'.");
            // a new line to get current state
           System.out.println("getCurrentState \'"+ getCurrentState() +"\'.");
}
```

run it and I get
> Transition from 'A' to 'B' on event 'ToB' with context '10'.
> Entry State 'B'.
> **getCurrentState 'A'.**
> Current state is B

Function "ontoB" called because state is entering "B", so I thought I should get state result as 'B'.
Am I misunderstanding this? or Is there an setting can alter this to what I expected?

I am using your great work in my app, thanks for making this.

**Comment by hekailiang** [comment]
Thanks for choosing squirrel state machine. State only changed when transition finished successfully which include exit original state, perform transition and enter new state. All these steps must be all executed successfully then state can be changed.

BTW, for further questions, I would suggest to post on [Squirrel Forum](https://groups.google.com/group/squirrel-state-machine) instead of creating a issue.
